// GENERATED by tool/gen_privacy_policy.mjs from frontend/src/pages/legal/legalContent.js. Do not edit by hand.

/// One section of the privacy policy: a heading and its paragraphs.
typedef PolicySection = ({String heading, List<String> paragraphs});

/// The website's "last reviewed" note (a placeholder until the operator publishes the policy).
const privacyReviewed = '9 October 2026';

/// The privacy policy in each app language: its title and sections.
const privacyPolicy = <String, ({String title, List<PolicySection> sections})>{
  'en': (
    title: 'Privacy Policy',
    sections: [
      (
        heading: 'Who we are',
        paragraphs: [
          'This service is operated by Dipesh Chouhan (the "Data Fiduciary" under the Digital Personal Data Protection Act, 2023). It helps ration card holders book a time to collect their ration, lets fair-price shops record collections, and lets government officials oversee distribution.',
        ],
      ),
      (
        heading: 'What we collect and why',
        paragraphs: [
          'Account: name, mobile number, email address and role, to sign you in.',
          'Ration records: ration card, family members, scheme and entitlement, bookings, tokens and collections, to provide your ration.',
          'Complaints: what you report, to resolve it and tell you the outcome.',
          'Aadhaar: the service only records whether Aadhaar is verified. Your Aadhaar number is never shown in full, and you are never asked to type it.',
          'We collect only what is needed for these purposes and do not use it for anything else.',
        ],
      ),
      (
        heading: 'Consent',
        paragraphs: [
          'By registering you consent to this processing for the purposes above. You can withdraw consent at any time by asking us to close your account (see "Your rights"); this does not affect processing already done or records the law requires us to keep.',
        ],
      ),
      (
        heading: 'Sharing',
        paragraphs: [
          'Your information is shared only to provide the ration service: with your ration shop (to serve you) and with government officials who oversee the public distribution system, and with others only where the law requires it. We do not sell your information. The service contains no advertising and no tracking tools.',
        ],
      ),
      (
        heading: 'Where and how long it is kept',
        paragraphs: [
          'Data is stored on servers located in India (Microsoft Azure, India South Central region). Records are kept for as long as your account is active and up to one year after it is closed, to provide the service and to handle complaints or disputes and then deleted or anonymised.',
        ],
      ),
      (
        heading: 'Security',
        paragraphs: [
          'Connections are encrypted (HTTPS, and TLS to the database). Passwords are stored only as secure hashes. Sign-in sessions expire. Important actions are recorded in an audit log that does not contain your messages or personal identifiers beyond what is needed.',
        ],
      ),
      (
        heading: 'Your rights',
        paragraphs: [
          'Under the DPDP Act you can ask to see a summary of your data, correct it, have it erased, and have a grievance addressed, and you may nominate a person to exercise these rights for you. Write to our Grievance Officer: Dipesh Chouhan, dipeshchouhan9146@gmail.com. We will reply within 30 days. If you are not satisfied you may approach the Data Protection Board of India.',
        ],
      ),
      (
        heading: 'Children',
        paragraphs: [
          'Accounts are for adults. Children\'s details appear only as family members on a ration card, are shown only to the card holder and the people who serve them, and are never used for any other purpose.',
        ],
      ),
      (
        heading: 'Changes',
        paragraphs: [
          'If this policy changes, the new version is published here with a new date.',
        ],
      ),
    ],
  ),
  'hi': (
    title: 'गोपनीयता नीति',
    sections: [
      (
        heading: 'हम कौन हैं',
        paragraphs: [
          'यह सेवा दीपेश चौहान द्वारा संचालित है (डिजिटल व्यक्तिगत डेटा संरक्षण अधिनियम, 2023 के तहत "डेटा फ़िड्यूशियरी")। यह राशन कार्ड धारकों को राशन लेने का समय बुक करने में, उचित मूल्य की दुकानों को वितरण दर्ज करने में और सरकारी अधिकारियों को वितरण की निगरानी में मदद करती है।',
        ],
      ),
      (
        heading: 'हम क्या लेते हैं और क्यों',
        paragraphs: [
          'खाता: नाम, मोबाइल नंबर, ईमेल और भूमिका, आपको साइन इन कराने के लिए।',
          'राशन रिकॉर्ड: राशन कार्ड, परिवार के सदस्य, योजना और हक, बुकिंग, टोकन और वितरण, आपको राशन देने के लिए।',
          'शिकायतें: आपने जो बताया, उसे सुलझाने और परिणाम बताने के लिए।',
          'आधार: सेवा केवल यह दर्ज करती है कि आधार सत्यापित है या नहीं। आपका आधार नंबर कभी पूरा नहीं दिखाया जाता और आपसे उसे लिखने को नहीं कहा जाता।',
          'हम इन उद्देश्यों के लिए केवल ज़रूरी जानकारी लेते हैं और उसका कोई और उपयोग नहीं करते।',
        ],
      ),
      (
        heading: 'सहमति',
        paragraphs: [
          'पंजीकरण करके आप ऊपर दिए उद्देश्यों के लिए इस प्रसंस्करण की सहमति देते हैं। आप कभी भी अपना खाता बंद करने को कहकर सहमति वापस ले सकते हैं ("आपके अधिकार" देखें); इससे पहले हो चुका प्रसंस्करण या कानून द्वारा ज़रूरी रिकॉर्ड प्रभावित नहीं होते।',
        ],
      ),
      (
        heading: 'साझा करना',
        paragraphs: [
          'आपकी जानकारी केवल राशन सेवा देने के लिए साझा की जाती है: आपकी राशन दुकान के साथ (आपको सेवा देने के लिए), सार्वजनिक वितरण प्रणाली की निगरानी करने वाले सरकारी अधिकारियों के साथ, और अन्य के साथ केवल तब जब कानून ऐसा माँगे। हम आपकी जानकारी नहीं बेचते। सेवा में कोई विज्ञापन या ट्रैकिंग टूल नहीं है।',
        ],
      ),
      (
        heading: 'कहाँ और कितने समय तक रखा जाता है',
        paragraphs: [
          'डेटा भारत (Microsoft Azure, India South Central क्षेत्र) में स्थित सर्वरों पर रखा जाता है। रिकॉर्ड जब तक आपका खाता सक्रिय है और बंद होने के बाद एक वर्ष तक, सेवा देने और शिकायतों या विवादों के निपटारे के लिए तक रखे जाते हैं और फिर हटा दिए जाते हैं या अनाम कर दिए जाते हैं।',
        ],
      ),
      (
        heading: 'सुरक्षा',
        paragraphs: [
          'कनेक्शन एन्क्रिप्टेड हैं (HTTPS, और डेटाबेस तक TLS)। पासवर्ड केवल सुरक्षित हैश के रूप में रखे जाते हैं। साइन-इन सत्र समाप्त हो जाते हैं। महत्वपूर्ण कार्य एक ऑडिट लॉग में दर्ज होते हैं जिसमें आपके संदेश या अनावश्यक व्यक्तिगत पहचान नहीं होती।',
        ],
      ),
      (
        heading: 'आपके अधिकार',
        paragraphs: [
          'DPDP अधिनियम के तहत आप अपने डेटा का सारांश देखने, उसे सुधारने, हटवाने और अपनी शिकायत का निवारण माँग सकते हैं, और इन अधिकारों के लिए किसी व्यक्ति को नामित कर सकते हैं। हमारे शिकायत अधिकारी को लिखें: दीपेश चौहान, dipeshchouhan9146@gmail.com। हम 30 दिनों में उत्तर देंगे। संतुष्ट न होने पर आप भारतीय डेटा संरक्षण बोर्ड से संपर्क कर सकते हैं।',
        ],
      ),
      (
        heading: 'बच्चे',
        paragraphs: [
          'खाते वयस्कों के लिए हैं। बच्चों का विवरण केवल राशन कार्ड पर परिवार के सदस्य के रूप में आता है, केवल कार्ड धारक और उन्हें सेवा देने वालों को दिखता है, और किसी और उद्देश्य के लिए उपयोग नहीं होता।',
        ],
      ),
      (
        heading: 'बदलाव',
        paragraphs: [
          'यह नीति बदलने पर नया संस्करण नई तारीख के साथ यहीं प्रकाशित किया जाएगा।',
        ],
      ),
    ],
  ),
  'mr': (
    title: 'गोपनीयता धोरण',
    sections: [
      (
        heading: 'आम्ही कोण आहोत',
        paragraphs: [
          'ही सेवा दीपेश चौहान चालवते (डिजिटल वैयक्तिक डेटा संरक्षण अधिनियम, 2023 अंतर्गत "डेटा फिड्युशियरी"). ती शिधापत्रिकाधारकांना रेशन घेण्याची वेळ बुक करण्यास, रास्त भाव दुकानांना वितरण नोंदवण्यास आणि सरकारी अधिकाऱ्यांना वितरणावर देखरेख ठेवण्यास मदत करते.',
        ],
      ),
      (
        heading: 'आम्ही काय घेतो आणि का',
        paragraphs: [
          'खाते: नाव, मोबाइल क्रमांक, ईमेल आणि भूमिका, तुम्हाला साइन इन करण्यासाठी.',
          'रेशन नोंदी: शिधापत्रिका, कुटुंबातील सदस्य, योजना आणि हक्क, बुकिंग, टोकन आणि वितरण, तुम्हाला रेशन देण्यासाठी.',
          'तक्रारी: तुम्ही कळवलेले, ते सोडवण्यासाठी आणि निकाल कळवण्यासाठी.',
          'आधार: सेवा फक्त आधार पडताळला आहे की नाही हे नोंदवते. तुमचा आधार क्रमांक कधीही पूर्ण दाखवला जात नाही आणि तो लिहायला सांगितले जात नाही.',
          'आम्ही या उद्देशांसाठी फक्त आवश्यक माहिती घेतो आणि तिचा इतर कोणताही वापर करत नाही.',
        ],
      ),
      (
        heading: 'संमती',
        paragraphs: [
          'नोंदणी करून तुम्ही वरील उद्देशांसाठी या प्रक्रियेस संमती देता. तुमचे खाते बंद करण्यास सांगून तुम्ही कधीही संमती मागे घेऊ शकता ("तुमचे अधिकार" पाहा); यामुळे आधी झालेली प्रक्रिया किंवा कायद्याने आवश्यक नोंदी प्रभावित होत नाहीत.',
        ],
      ),
      (
        heading: 'सामायिकरण',
        paragraphs: [
          'तुमची माहिती फक्त रेशन सेवा देण्यासाठी सामायिक केली जाते: तुमच्या रेशन दुकानासोबत (तुम्हाला सेवा देण्यासाठी), सार्वजनिक वितरण प्रणालीवर देखरेख ठेवणाऱ्या सरकारी अधिकाऱ्यांसोबत, आणि इतरांसोबत फक्त कायद्याने आवश्यक असेल तेव्हा. आम्ही तुमची माहिती विकत नाही. सेवेत कोणतीही जाहिरात किंवा ट्रॅकिंग साधने नाहीत.',
        ],
      ),
      (
        heading: 'कुठे आणि किती काळ ठेवली जाते',
        paragraphs: [
          'डेटा भारत (Microsoft Azure, India South Central प्रदेश) येथील सर्व्हरवर ठेवला जातो. नोंदी तुमचे खाते सक्रिय असेपर्यंत आणि बंद झाल्यानंतर एक वर्षापर्यंत, सेवा देण्यासाठी आणि तक्रारी किंवा वाद सोडवण्यासाठी ठेवल्या जातात आणि नंतर हटवल्या किंवा अनामिक केल्या जातात.',
        ],
      ),
      (
        heading: 'सुरक्षा',
        paragraphs: [
          'जोडण्या एन्क्रिप्टेड आहेत (HTTPS, आणि डेटाबेसपर्यंत TLS). पासवर्ड फक्त सुरक्षित हॅश स्वरूपात ठेवले जातात. साइन-इन सत्रे कालबाह्य होतात. महत्त्वाच्या कृती ऑडिट लॉगमध्ये नोंदवल्या जातात ज्यात तुमचे संदेश किंवा अनावश्यक वैयक्तिक ओळख नसते.',
        ],
      ),
      (
        heading: 'तुमचे अधिकार',
        paragraphs: [
          'DPDP अधिनियमानुसार तुम्ही तुमच्या डेटाचा सारांश पाहणे, तो दुरुस्त करणे, हटवणे आणि तक्रार निवारण मागू शकता, आणि या अधिकारांसाठी एखाद्या व्यक्तीला नामनिर्देशित करू शकता. आमच्या तक्रार अधिकाऱ्याला लिहा: दीपेश चौहान, dipeshchouhan9146@gmail.com. आम्ही 30 दिवसांत उत्तर देऊ. समाधान न झाल्यास तुम्ही भारतीय डेटा संरक्षण मंडळाकडे जाऊ शकता.',
        ],
      ),
      (
        heading: 'मुले',
        paragraphs: [
          'खाती प्रौढांसाठी आहेत. मुलांचा तपशील फक्त शिधापत्रिकेवरील कुटुंब सदस्य म्हणून येतो, फक्त पत्रिकाधारक आणि त्यांना सेवा देणाऱ्यांना दिसतो, आणि इतर कोणत्याही उद्देशासाठी वापरला जात नाही.',
        ],
      ),
      (
        heading: 'बदल',
        paragraphs: [
          'हे धोरण बदलल्यास नवीन आवृत्ती नवीन तारखेसह येथेच प्रकाशित केली जाईल.',
        ],
      ),
    ],
  ),
};
