// Writes lib/features/legal/privacy_text.dart from the website's privacy policy (frontend/src/pages/legal/legalContent.js),
// so the app shows the same text people consent to on the website. Run after the website's policy changes:
//   node tool/gen_privacy_policy.mjs        (from smart_ration_mobile/)
// test/features/privacy_text_test.dart fails if the two drift apart.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "..", "..", "frontend", "src", "pages", "legal", "legalContent.js");
const { legalContent, LEGAL_REVIEWED } = await import(pathToFileURL(source).href);

const dart = (s) => `'${s.replaceAll("\\", "\\\\").replaceAll("'", "\\'").replaceAll("$", "\\$").replaceAll("\n", "\\n")}'`;

let out = `// GENERATED by tool/gen_privacy_policy.mjs from frontend/src/pages/legal/legalContent.js. Do not edit by hand.

/// One section of the privacy policy: a heading and its paragraphs.
typedef PolicySection = ({String heading, List<String> paragraphs});

/// The website's "last reviewed" note (a placeholder until the operator publishes the policy).
const privacyReviewed = ${dart(LEGAL_REVIEWED)};

/// The privacy policy in each app language: its title and sections.
const privacyPolicy = <String, ({String title, List<PolicySection> sections})>{
`;
for (const lang of ["en", "hi", "mr"]) {
  const p = legalContent[lang].privacy;
  out += `  '${lang}': (\n    title: ${dart(p.title)},\n    sections: [\n`;
  for (const [heading, paragraphs] of p.sections) {
    out += `      (\n        heading: ${dart(heading)},\n        paragraphs: [\n`;
    for (const para of paragraphs) out += `          ${dart(para)},\n`;
    out += `        ],\n      ),\n`;
  }
  out += `    ],\n  ),\n`;
}
out += `};\n`;

const target = join(here, "..", "lib", "features", "legal", "privacy_text.dart");
writeFileSync(target, out, "utf8");
console.log(`wrote ${target}`);
