"""Initial schema: the 25 Smart Ration tables exactly as they exist in MySQL.

Generated by `alembic revision --autogenerate` from app/models/, which is
itself verified column-for-column against the live database
(tests/integration/test_schema_compat.py). Constraint names follow EF Core's convention,
so a database created here is identical to the existing one.

* Fresh database  -> `alembic upgrade head` creates everything.
* Existing database (created earlier by the C# API / EF Core) -> NOT upgraded:
  scripts/setup_database.py verifies it matches and runs `alembic stamp 0001_initial`
  (adds only the alembic_version table; no data or tables are touched).

Downgrading this revision drops every table. It is refused unless
RESET_DATABASE=true and CONFIRM_RESET=SMART_RATION_RESET are both set
(use scripts/reset_database.py, which also takes a backup first).

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-24
"""
import os

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AIAlerts',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ShopId', sa.Integer(), nullable=True),
    sa.Column('BeneficiaryId', sa.Integer(), nullable=True),
    sa.Column('AlertType', sa.String(length=64), nullable=False),
    sa.Column('Severity', sa.Integer(), nullable=False),
    sa.Column('Description', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Status', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('ResolvedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('Source', sa.String(length=32), server_default='RULES', nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=True),
    sa.Column('RationType', sa.Integer(), nullable=True),
    sa.Column('Score', sa.Double(), nullable=True),
    sa.Column('RecommendedAction', sa.String(length=500), nullable=True),
    sa.Column('DedupKey', sa.String(length=128), nullable=True),
    sa.Column('MetadataJson', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('DetectedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('LastSeenAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('ResolvedByUserId', sa.Integer(), nullable=True),
    sa.Column('ResolutionNote', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_AIAlerts_DedupKey_Status', 'AIAlerts', ['DedupKey', 'Status'], unique=False)
    op.create_index('IX_AIAlerts_ShopId_Status', 'AIAlerts', ['ShopId', 'Status'], unique=False)
    op.create_table('AIInsights',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EntityType', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('EntityId', sa.Integer(), nullable=True),
    sa.Column('InsightType', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('RiskLevel', sa.Integer(), nullable=False),
    sa.Column('Score', sa.Double(), nullable=False),
    sa.Column('Explanation', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Recommendation', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('AuditLogs',
    sa.Column('Id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('Action', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('EntityName', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('EntityId', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('IpAddress', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('Details', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('Role', sa.String(length=32), nullable=True),
    sa.Column('Result', sa.String(length=16), nullable=True),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('RationItems',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RationType', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('VernacularName', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Unit', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('StandardQuotaPerBooking', sa.Numeric(precision=65, scale=30), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_RationItems_RationType', 'RationItems', ['RationType'], unique=True)
    op.create_table('RationSchemes',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SchemeCode', sa.String(length=255), nullable=False),
    sa.Column('Name', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Description', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_RationSchemes_SchemeCode', 'RationSchemes', ['SchemeCode'], unique=True)
    op.create_table('RationShops',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ShopName', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('ShopCode', sa.String(length=255), nullable=False),
    sa.Column('Address', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('District', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('State', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Taluka', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('Village', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('Latitude', sa.Double(), nullable=False),
    sa.Column('Longitude', sa.Double(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_RationShops_ShopCode', 'RationShops', ['ShopCode'], unique=True)
    op.create_table('VerificationAuditLogs',
    sa.Column('Id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('VerificationReference', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('TokenNumber', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('BeneficiaryId', sa.Integer(), nullable=True),
    sa.Column('ShopId', sa.Integer(), nullable=True),
    sa.Column('Action', sa.Integer(), nullable=False),
    sa.Column('VerificationMethod', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Status', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Reason', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('OperatorId', sa.Integer(), nullable=True),
    sa.Column('DeviceInfo', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('IpAddress', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('Timestamp', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Families',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FamilyCode', sa.String(length=255), nullable=False),
    sa.Column('RationShopId', sa.Integer(), nullable=False),
    sa.Column('RationSchemeId', sa.Integer(), nullable=False),
    sa.Column('DataSource', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['RationSchemeId'], ['RationSchemes.Id'], name=op.f('FK_Families_RationSchemes_RationSchemeId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['RationShopId'], ['RationShops.Id'], name=op.f('FK_Families_RationShops_RationShopId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_Families_FamilyCode', 'Families', ['FamilyCode'], unique=True)
    op.create_index('IX_Families_RationSchemeId', 'Families', ['RationSchemeId'], unique=False)
    op.create_index('IX_Families_RationShopId', 'Families', ['RationShopId'], unique=False)
    op.create_table('Inventory',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RationShopId', sa.Integer(), nullable=False),
    sa.Column('RationType', sa.Integer(), nullable=False),
    sa.Column('AvailableQuantity', sa.Numeric(precision=65, scale=30), nullable=False),
    sa.Column('AllocatedQuantity', sa.Numeric(precision=65, scale=30), nullable=False),
    sa.Column('MinimumStockLevel', sa.Numeric(precision=65, scale=30), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['RationShopId'], ['RationShops.Id'], name=op.f('FK_Inventory_RationShops_RationShopId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_Inventory_RationShopId_RationType', 'Inventory', ['RationShopId', 'RationType'], unique=True)
    op.create_table('InventoryMovements',
    sa.Column('Id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('RationShopId', sa.Integer(), nullable=False),
    sa.Column('RationType', sa.Integer(), nullable=False),
    sa.Column('MovementType', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Numeric(precision=65, scale=30), nullable=False),
    sa.Column('BalanceAfter', sa.Numeric(precision=65, scale=30), nullable=False),
    sa.Column('Reference', sa.String(length=64), nullable=True),
    sa.Column('Note', sa.String(length=256), nullable=True),
    sa.Column('RecordedByUserId', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['RationShopId'], ['RationShops.Id'], name=op.f('FK_InventoryMovements_RationShops_RationShopId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_InventoryMovements_RationShopId_RationType_CreatedAt', 'InventoryMovements', ['RationShopId', 'RationType', 'CreatedAt'], unique=False)
    op.create_table('SchemeEntitlementItems',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RationSchemeId', sa.Integer(), nullable=False),
    sa.Column('RationType', sa.Integer(), nullable=False),
    sa.Column('QuotaPerEligibleMemberPerMonth', sa.Numeric(precision=65, scale=30), nullable=False),
    sa.ForeignKeyConstraint(['RationSchemeId'], ['RationSchemes.Id'], name=op.f('FK_SchemeEntitlementItems_RationSchemes_RationSchemeId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_SchemeEntitlementItems_RationSchemeId_RationType', 'SchemeEntitlementItems', ['RationSchemeId', 'RationType'], unique=True)
    op.create_table('TimeSlots',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RationShopId', sa.Integer(), nullable=False),
    sa.Column('SlotDate', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('StartTime', sa.Time().with_variant(mysql.TIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('EndTime', sa.Time().with_variant(mysql.TIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('Capacity', sa.Integer(), nullable=False),
    sa.Column('BookedCount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RationShopId'], ['RationShops.Id'], name=op.f('FK_TimeSlots_RationShops_RationShopId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_TimeSlots_RationShopId', 'TimeSlots', ['RationShopId'], unique=False)
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FullName', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('MobileNumber', sa.String(length=255), nullable=False),
    sa.Column('PasswordHash', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Role', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('RationShopId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RationShopId'], ['RationShops.Id'], name=op.f('FK_Users_RationShops_RationShopId'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_Users_Email', 'Users', ['Email'], unique=True)
    op.create_index('IX_Users_MobileNumber', 'Users', ['MobileNumber'], unique=True)
    op.create_index('IX_Users_RationShopId', 'Users', ['RationShopId'], unique=False)
    op.create_table('Beneficiaries',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BeneficiaryCode', sa.String(length=255), nullable=False),
    sa.Column('Address', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Gender', sa.Integer(), nullable=False),
    sa.Column('DateOfBirth', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('Village', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('District', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('State', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Pincode', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('ProfilePhotoUrl', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('FamilyId', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('IsBlocked', sa.Boolean(), nullable=False),
    sa.Column('DataSource', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['FamilyId'], ['Families.Id'], name=op.f('FK_Beneficiaries_Families_FamilyId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], name=op.f('FK_Beneficiaries_Users_UserId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_Beneficiaries_BeneficiaryCode', 'Beneficiaries', ['BeneficiaryCode'], unique=True)
    op.create_index('IX_Beneficiaries_FamilyId', 'Beneficiaries', ['FamilyId'], unique=False)
    op.create_index('IX_Beneficiaries_UserId', 'Beneficiaries', ['UserId'], unique=True)
    op.create_table('FamilyMembers',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FamilyId', sa.Integer(), nullable=False),
    sa.Column('FullName', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.Column('Relationship', sa.Integer(), nullable=False),
    sa.Column('Eligibility', sa.Integer(), nullable=False),
    sa.Column('DataSource', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['FamilyId'], ['Families.Id'], name=op.f('FK_FamilyMembers_Families_FamilyId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_FamilyMembers_FamilyId', 'FamilyMembers', ['FamilyId'], unique=False)
    op.create_table('Notifications',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Type', sa.Integer(), nullable=False),
    sa.Column('Title', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Message', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('IsRead', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], name=op.f('FK_Notifications_Users_UserId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_Notifications_UserId', 'Notifications', ['UserId'], unique=False)
    op.create_table('RefreshTokens',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('TokenHash', sa.String(length=255), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('RevokedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('ReplacedByTokenHash', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], name=op.f('FK_RefreshTokens_Users_UserId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_RefreshTokens_TokenHash', 'RefreshTokens', ['TokenHash'], unique=True)
    op.create_index('IX_RefreshTokens_UserId', 'RefreshTokens', ['UserId'], unique=False)
    op.create_table('Tokens',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TokenNumber', sa.String(length=255), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('RationShopId', sa.Integer(), nullable=False),
    sa.Column('TimeSlotId', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Integer(), nullable=False),
    sa.Column('QRCodeValue', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('CollectedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['RationShopId'], ['RationShops.Id'], name=op.f('FK_Tokens_RationShops_RationShopId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['TimeSlotId'], ['TimeSlots.Id'], name=op.f('FK_Tokens_TimeSlots_TimeSlotId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], name=op.f('FK_Tokens_Users_UserId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_Tokens_RationShopId', 'Tokens', ['RationShopId'], unique=False)
    op.create_index('IX_Tokens_TimeSlotId', 'Tokens', ['TimeSlotId'], unique=False)
    op.create_index('IX_Tokens_TokenNumber', 'Tokens', ['TokenNumber'], unique=True)
    op.create_index('IX_Tokens_UserId', 'Tokens', ['UserId'], unique=False)
    op.create_table('AadhaarVerifications',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BeneficiaryId', sa.Integer(), nullable=False),
    sa.Column('AadhaarReferenceId', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('AadhaarMasked', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Status', sa.Integer(), nullable=False),
    sa.Column('VerificationDate', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('VerificationSource', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('VerificationMode', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['BeneficiaryId'], ['Beneficiaries.Id'], name=op.f('FK_AadhaarVerifications_Beneficiaries_BeneficiaryId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_AadhaarVerifications_BeneficiaryId', 'AadhaarVerifications', ['BeneficiaryId'], unique=True)
    op.create_table('MobileVerifications',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BeneficiaryId', sa.Integer(), nullable=False),
    sa.Column('MobileMasked', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Status', sa.Integer(), nullable=False),
    sa.Column('VerifiedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('VerificationSource', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['BeneficiaryId'], ['Beneficiaries.Id'], name=op.f('FK_MobileVerifications_Beneficiaries_BeneficiaryId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_MobileVerifications_BeneficiaryId', 'MobileVerifications', ['BeneficiaryId'], unique=True)
    op.create_table('OtpVerifications',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BeneficiaryId', sa.Integer(), nullable=False),
    sa.Column('RequestedByUserId', sa.Integer(), nullable=False),
    sa.Column('OtpHash', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('AttemptCount', sa.Integer(), nullable=False),
    sa.Column('MaxAttempts', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('VerifiedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['BeneficiaryId'], ['Beneficiaries.Id'], name=op.f('FK_OtpVerifications_Beneficiaries_BeneficiaryId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_OtpVerifications_BeneficiaryId', 'OtpVerifications', ['BeneficiaryId'], unique=False)
    op.create_table('PassbookVerifications',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BeneficiaryId', sa.Integer(), nullable=False),
    sa.Column('PassbookNumber', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('Status', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('VerificationStatus', sa.Integer(), nullable=False),
    sa.Column('LastUpdated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('VerificationSource', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['BeneficiaryId'], ['Beneficiaries.Id'], name=op.f('FK_PassbookVerifications_Beneficiaries_BeneficiaryId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_PassbookVerifications_BeneficiaryId', 'PassbookVerifications', ['BeneficiaryId'], unique=True)
    op.create_table('RationCollections',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CollectionCode', sa.String(length=255), nullable=False),
    sa.Column('TokenId', sa.Integer(), nullable=False),
    sa.Column('BeneficiaryId', sa.Integer(), nullable=False),
    sa.Column('RationShopId', sa.Integer(), nullable=False),
    sa.Column('OperatorUserId', sa.Integer(), nullable=False),
    sa.Column('VerificationMethod', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('CollectedAt', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('IdempotencyKey', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['BeneficiaryId'], ['Beneficiaries.Id'], name=op.f('FK_RationCollections_Beneficiaries_BeneficiaryId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['RationShopId'], ['RationShops.Id'], name=op.f('FK_RationCollections_RationShops_RationShopId'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['TokenId'], ['Tokens.Id'], name=op.f('FK_RationCollections_Tokens_TokenId'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_RationCollections_BeneficiaryId', 'RationCollections', ['BeneficiaryId'], unique=False)
    op.create_index('IX_RationCollections_CollectionCode', 'RationCollections', ['CollectionCode'], unique=True)
    op.create_index('IX_RationCollections_IdempotencyKey', 'RationCollections', ['IdempotencyKey'], unique=True)
    op.create_index('IX_RationCollections_RationShopId', 'RationCollections', ['RationShopId'], unique=False)
    op.create_index('IX_RationCollections_TokenId', 'RationCollections', ['TokenId'], unique=True)
    op.create_table('TokenItems',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TokenId', sa.Integer(), nullable=False),
    sa.Column('RationType', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Numeric(precision=65, scale=30), nullable=False),
    sa.ForeignKeyConstraint(['TokenId'], ['Tokens.Id'], name=op.f('FK_TokenItems_Tokens_TokenId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_TokenItems_TokenId', 'TokenItems', ['TokenId'], unique=False)
    op.create_table('RationCollectionItems',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RationCollectionId', sa.Integer(), nullable=False),
    sa.Column('RationType', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Numeric(precision=65, scale=30), nullable=False),
    sa.ForeignKeyConstraint(['RationCollectionId'], ['RationCollections.Id'], name=op.f('FK_RationCollectionItems_RationCollections_RationCollectionId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_RationCollectionItems_RationCollectionId', 'RationCollectionItems', ['RationCollectionId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    if os.environ.get("RESET_DATABASE") != "true" or os.environ.get("CONFIRM_RESET") != "SMART_RATION_RESET":
        raise RuntimeError(
            "Refusing to drop every Smart Ration table. Set RESET_DATABASE=true and "
            "CONFIRM_RESET=SMART_RATION_RESET (or use scripts/reset_database.py, which backs up first)."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IX_RationCollectionItems_RationCollectionId', table_name='RationCollectionItems')
    op.drop_table('RationCollectionItems')
    op.drop_index('IX_TokenItems_TokenId', table_name='TokenItems')
    op.drop_table('TokenItems')
    op.drop_index('IX_RationCollections_TokenId', table_name='RationCollections')
    op.drop_index('IX_RationCollections_RationShopId', table_name='RationCollections')
    op.drop_index('IX_RationCollections_IdempotencyKey', table_name='RationCollections')
    op.drop_index('IX_RationCollections_CollectionCode', table_name='RationCollections')
    op.drop_index('IX_RationCollections_BeneficiaryId', table_name='RationCollections')
    op.drop_table('RationCollections')
    op.drop_index('IX_PassbookVerifications_BeneficiaryId', table_name='PassbookVerifications')
    op.drop_table('PassbookVerifications')
    op.drop_index('IX_OtpVerifications_BeneficiaryId', table_name='OtpVerifications')
    op.drop_table('OtpVerifications')
    op.drop_index('IX_MobileVerifications_BeneficiaryId', table_name='MobileVerifications')
    op.drop_table('MobileVerifications')
    op.drop_index('IX_AadhaarVerifications_BeneficiaryId', table_name='AadhaarVerifications')
    op.drop_table('AadhaarVerifications')
    op.drop_index('IX_Tokens_UserId', table_name='Tokens')
    op.drop_index('IX_Tokens_TokenNumber', table_name='Tokens')
    op.drop_index('IX_Tokens_TimeSlotId', table_name='Tokens')
    op.drop_index('IX_Tokens_RationShopId', table_name='Tokens')
    op.drop_table('Tokens')
    op.drop_index('IX_RefreshTokens_UserId', table_name='RefreshTokens')
    op.drop_index('IX_RefreshTokens_TokenHash', table_name='RefreshTokens')
    op.drop_table('RefreshTokens')
    op.drop_index('IX_Notifications_UserId', table_name='Notifications')
    op.drop_table('Notifications')
    op.drop_index('IX_FamilyMembers_FamilyId', table_name='FamilyMembers')
    op.drop_table('FamilyMembers')
    op.drop_index('IX_Beneficiaries_UserId', table_name='Beneficiaries')
    op.drop_index('IX_Beneficiaries_FamilyId', table_name='Beneficiaries')
    op.drop_index('IX_Beneficiaries_BeneficiaryCode', table_name='Beneficiaries')
    op.drop_table('Beneficiaries')
    op.drop_index('IX_Users_RationShopId', table_name='Users')
    op.drop_index('IX_Users_MobileNumber', table_name='Users')
    op.drop_index('IX_Users_Email', table_name='Users')
    op.drop_table('Users')
    op.drop_index('IX_TimeSlots_RationShopId', table_name='TimeSlots')
    op.drop_table('TimeSlots')
    op.drop_index('IX_SchemeEntitlementItems_RationSchemeId_RationType', table_name='SchemeEntitlementItems')
    op.drop_table('SchemeEntitlementItems')
    op.drop_index('IX_InventoryMovements_RationShopId_RationType_CreatedAt', table_name='InventoryMovements')
    op.drop_table('InventoryMovements')
    op.drop_index('IX_Inventory_RationShopId_RationType', table_name='Inventory')
    op.drop_table('Inventory')
    op.drop_index('IX_Families_RationShopId', table_name='Families')
    op.drop_index('IX_Families_RationSchemeId', table_name='Families')
    op.drop_index('IX_Families_FamilyCode', table_name='Families')
    op.drop_table('Families')
    op.drop_table('VerificationAuditLogs')
    op.drop_index('IX_RationShops_ShopCode', table_name='RationShops')
    op.drop_table('RationShops')
    op.drop_index('IX_RationSchemes_SchemeCode', table_name='RationSchemes')
    op.drop_table('RationSchemes')
    op.drop_index('IX_RationItems_RationType', table_name='RationItems')
    op.drop_table('RationItems')
    op.drop_table('AuditLogs')
    op.drop_table('AIInsights')
    op.drop_index('IX_AIAlerts_ShopId_Status', table_name='AIAlerts')
    op.drop_index('IX_AIAlerts_DedupKey_Status', table_name='AIAlerts')
    op.drop_table('AIAlerts')
    # ### end Alembic commands ###
