using SmartRation.Api.Services;

namespace SmartRation.Api.Tests;

// The Python backend upgrades hashes to Argon2id; this API must still verify them.
public class PasswordHashesTests
{
    // Generated by the Python backend (argon2-cffi defaults) for the password "demo123".
    private const string PythonArgon2Hash = "$argon2id$v=19$m=65536,t=3,p=4$1H0YrYum849gyirKpJ1CmQ$mhgh6v6hb69FcqWjDVNziixxNyab77+mbJ8xrNF0gMg";

    [Fact]
    public void Verifies_Argon2_Hash_From_Python() =>
        Assert.True(PasswordHashes.Verify("demo123", PythonArgon2Hash));

    [Fact]
    public void Rejects_Wrong_Password_For_Argon2() =>
        Assert.False(PasswordHashes.Verify("wrong-password", PythonArgon2Hash));

    [Fact]
    public void Still_Verifies_BCrypt()
    {
        var hash = BCrypt.Net.BCrypt.HashPassword("demo123");
        Assert.True(PasswordHashes.Verify("demo123", hash));
        Assert.False(PasswordHashes.Verify("nope", hash));
    }

    [Theory]
    [InlineData("")]
    [InlineData("$argon2id$garbage")]
    [InlineData("not-a-hash")]
    public void Malformed_Hashes_Fail_Closed(string hash) =>
        Assert.False(PasswordHashes.Verify("demo123", hash));
}
